### ISSUE TITLE
4.19.8 error build

### ISSUE THREAD

**Issue by Defortio** [zen-kernel/zen-kernel#133]
```
GEN     .version
  CHK     include/generated/compile.h
  AR      built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.o
ld: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x28): undefined reference to `sched_smt_present'
ld: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x40): undefined reference to `sched_smt_present'
make[2]: *** [Makefile:1032: vmlinux] Error 1

```
in build 4.19.8 afte build with has error 4.19.7 - error repeated

Built on Opensuse Tumbleweed

**Comment by heftig** [comment]
Duplicate of #132
