### ISSUE TITLE
built-in.a(arch/x86/kernel/cpu/bugs.o)(__jump_table+0x28): error: undefined reference to 'sched_smt_present'

### ISSUE THREAD

**Issue by perfect7gentleman** [zen-kernel/zen-kernel#132]
```
  GEN     .version
  CHK     include/generated/compile.h
  AR      built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.o
built-in.a(arch/x86/kernel/cpu/bugs.o)(__jump_table+0x28): error: undefined reference to 'sched_smt_present'
built-in.a(arch/x86/kernel/cpu/bugs.o)(__jump_table+0x40): error: undefined reference to 'sched_smt_present'
built-in.a(arch/x86/kernel/cpu/bugs.o)(__jump_table+0x58): error: undefined reference to 'sched_smt_present'
built-in.a(arch/x86/kernel/cpu/bugs.o)(__jump_table+0x70): error: undefined reference to 'sched_smt_present'
```
Built on Gentoo. 4.19.6 was build fine.

**Comment by Defortio** [comment]
I have this problem too!
Built on Opensuse Tumbleweed. with 4.19.6 don't has problem

**Comment by lmy441900** [comment]
I have the same problem on 4.19.7-zen1.

```
  GEN     .version
  CHK     include/generated/compile.h
  AR      built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.o
arch/x86/kernel/cpu/bugs.o:(__jump_table+0x28): undefined reference to `sched_smt_present'
arch/x86/kernel/cpu/bugs.o:(__jump_table+0x40): undefined reference to `sched_smt_present'
arch/x86/kernel/cpu/bugs.o:(__jump_table+0x58): undefined reference to `sched_smt_present'
arch/x86/kernel/cpu/bugs.o:(__jump_table+0x70): undefined reference to `sched_smt_present'
arch/x86/kernel/cpu/bugs.o:(__jump_table+0x88): undefined reference to `sched_smt_present'
arch/x86/kernel/cpu/bugs.o:(__jump_table+0xa0): more undefined references to `sched_smt_present' follow
make: *** [Makefile:1036: vmlinux] Error 1
```

This problem also presents on Linux Kernel with CK patches applied.

I dug into the source code a little. Consider changes being made from 4.19.6 on, torvalds/linux@340693e should be the commit causing problem, where `extern struct static_key_false sched_smt_present` is moved from `kernel/sched/sched.h` to `include/linux/sched/smt.h`.

**Comment by heftig** [comment]
I'll wait for CK to fix this.

**Comment by Defortio** [comment]
```
GEN     .version
  CHK     include/generated/compile.h
  AR      built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.o
ld: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x28): undefined reference to `sched_smt_present'
ld: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x40): undefined reference to `sched_smt_present'
make[2]: *** [Makefile:1032: vmlinux] Error 1
```

in build 4.19.8 afte build with has error 4.19.7 - error repeated

Built on Opensuse Tumbleweed

**Comment by Tomoms** [comment]
I'm facing the same issue, building openSuSE Tumbleweed's kernel with zen's patches.

**Comment by damentz** [comment]
Has anyone's builds since https://github.com/zen-kernel/zen-kernel/commit/9c460cd2 succeeded?  My builds with MuQSS enabled complete their builds without any errors.  In fact, I'm running my own 4.19.8 build to write this comment.

**Comment by heftig** [comment]
Note that with `sched_smt_present` always being `0` for MuQSS, the mitigations for SMT-specific vulnerabilities are always disabled. Something to keep in mind when comparing benchmarks with CFS.

**Comment by Defortio** [comment]
> Has anyone's builds since [9c460cd](https://github.com/zen-kernel/zen-kernel/commit/9c460cd2) succeeded? My builds with MuQSS enabled complete without errors. In fact, I'm running my own 4.19.8 build to write this comment.

![err](https://user-images.githubusercontent.com/40630996/49721724-e1c76f00-fc5a-11e8-8cda-fe3d677f6b73.png)
MuQSS enabled - have error

**Comment by Defortio** [comment]
> Has anyone's builds since [9c460cd](https://github.com/zen-kernel/zen-kernel/commit/9c460cd2) succeeded? My builds with MuQSS enabled complete without errors. In fact, I'm running my own 4.19.8 build to write this comment.

for test - build with disable MuQSS - without error

**Comment by Tomoms** [comment]
> Has anyone's builds since [9c460cd](https://github.com/zen-kernel/zen-kernel/commit/9c460cd2) succeeded? My builds with MuQSS enabled complete without errors. In fact, I'm running my own 4.19.8 build to write this comment.

I've built 4.19.7 with that patch and the build succeeded. I'm now running the kernel and it's working perfectly. Thank you :)

**Comment by lmy441900** [comment]
> Has anyone's builds since [9c460cd](https://github.com/zen-kernel/zen-kernel/commit/9c460cd2) succeeded?

Yes the build succeed after this patch applied (actually I found the same patch from https://pastebin.com/v618N2xd).

**Comment by Defortio** [comment]
after add patch < - all work

**Comment by damentz** [comment]
Excellent!  Thanks for all the feedback.  Closing out this issue.
