### ISSUE TITLE
The BFS scheduler does not compile on 4.0.4

### ISSUE THREAD

**Issue by bogdanr** [zen-kernel/zen-kernel#24]
When compiling the BFS scheduler an *undefined reference to `register_task_migration_notifier'* error will be produced and the kernel will not compile.

This is fixed by this patch:
http://ck.kolivas.org/patches/bfs/4.0/4.0/pending/bfs462-rtmn-fix.patch

**Comment by heftig** [comment]
Fixed, thanks.
