### ISSUE TITLE
Bad merge of '5.4/upstream-updates' into 5.4/master

### ISSUE THREAD

**Issue by Techwolf** [zen-kernel/zen-kernel#168]
I got an error of this:

```
drivers/acpi/sleep.c: In function ‘acpi_s2idle_wake’:
drivers/acpi/sleep.c:988:1: warning: no return statement in function returning non-void [-Wreturn-type]
  988 | }
      | ^
drivers/acpi/sleep.c: At top level:
drivers/acpi/sleep.c:990:1: error: expected identifier or ‘(’ before ‘{’ token
  990 | {
      | ^
drivers/acpi/sleep.c: In function ‘acpi_s2idle_restore’:
drivers/acpi/sleep.c:1067:2: error: implicit declaration of function ‘acpi_s2idle_sync’; did you mean ‘acpi_s2idle_wake’? [-Werror=implicit-function-declaration]
 1067 |  acpi_s2idle_sync();
      |  ^~~~~~~~~~~~~~~~
      |  acpi_s2idle_wake
  CC      arch/x86/lib/cmdline.o
cc1: some warnings being treated as errors
  AR      drivers/clocksource/built-in.a
make[2]: *** [scripts/Makefile.build:266: drivers/acpi/sleep.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Doing a bit of debugging work pointed to a bad merge.

```
diff -up ./drivers/acpi/sleep.c.org ./drivers/acpi/sleep.c
--- ./drivers/acpi/sleep.c.org  2020-03-20 18:19:05.877602597 -0400
+++ ./drivers/acpi/sleep.c      2020-03-20 20:23:21.191085857 -0400
@@ -977,7 +977,7 @@ static int acpi_s2idle_prepare_late(void
        return 0;
 }
 
-static bool acpi_s2idle_wake(void)
+static void acpi_s2idle_sync(void)
 {
        /*
         * The EC driver uses the system workqueue and an additional special
@@ -987,6 +987,7 @@ static bool acpi_s2idle_wake(void)
        acpi_os_wait_events_complete(); /* synchronize Notify handling */
 }
 
+static bool acpi_s2idle_wake(void)
 {
        if (!acpi_sci_irq_valid())
                return pm_wakeup_pending();
```

**Comment by damentz** [comment]
@Techwolf thanks for debugging, I used your changes to fix the merge.  On top of that I merged the latest stable updates.
