### ISSUE TITLE
Error! Bad return status for module build on kernel: 6.15.2-zen1-1-zen (x86_64)

### ISSUE THREAD

**Issue by tetoNidan** [zen-kernel/zen-kernel#385]
During update I noticed this `Error` and thought I should report it.

```
dkms install --no-depmod v4l2loopback-dc/2.1.3 -k 6.15.2-zen1-1-zen
Deprecated feature: CLEAN (/var/lib/dkms/v4l2loopback-dc/2.1.3/source/dkms.conf)

Error! Bad return status for module build on kernel: 6.15.2-zen1-1-zen (x86_64)
Consult /var/lib/dkms/v4l2loopback-dc/2.1.3/build/make.log for more information.
```

Here is the `/var/lib/dkms/v4l2loopback-dc/2.1.3/build/make.log`:

```
cat /var/lib/dkms/v4l2loopback-dc/2.1.3/build/make.log
DKMS (dkms-3.2.1) make.log for v4l2loopback-dc/2.1.3 for kernel 6.15.2-zen1-1-zen (x86_64)
Thu Jun 12 08:43:19 PM MDT 2025

Building module(s)
# command: make -j16 KERNELRELEASE=6.15.2-zen1-1-zen all
make -C /lib/modules/6.15.2-zen1-1-zen/build M=/var/lib/dkms/v4l2loopback-dc/2.1.3/build modules
make[1]: Entering directory '/usr/lib/modules/6.15.2-zen1-1-zen/build'
make[2]: Entering directory '/var/lib/dkms/v4l2loopback-dc/2.1.3/build'
  CC [M]  v4l2loopback-dc.o
v4l2loopback-dc.c: In function ‘buffer_written’:
v4l2loopback-dc.c:1514:3: error: implicit declaration of function ‘del_timer_sync’ [-Wimplicit-function-declaration]
 1514 |   del_timer_sync(&dev->sustain_timer);
      |   ^~~~~~~~~~~~~~
v4l2loopback-dc.c: At top level:
v4l2loopback-dc.c:2347:4: error: ‘const struct v4l2_ioctl_ops’ has no member named ‘vidioc_queryctrl’; did you mean ‘vidioc_querycap’?
 2347 |   .vidioc_queryctrl         = &vidioc_queryctrl,
      |    ^~~~~~~~~~~~~~~~
      |    vidioc_querycap
v4l2loopback-dc.c:2347:31: error: initialization of ‘int (*)(struct file *, void *, struct v4l2_dv_timings *)’ from incompatible pointer type ‘int (*)(struct file *, void *, struct v4l2_queryctrl *)’ [-Wincompatible-pointer-types]
 2347 |   .vidioc_queryctrl         = &vidioc_queryctrl,
      |                               ^
v4l2loopback-dc.c:2347:31: note: (near initialization for ‘v4l2_loopback_ioctl_ops.vidioc_s_dv_timings’)
v4l2loopback-dc.c:1151:1: note: ‘vidioc_queryctrl’ declared here
 1151 | vidioc_queryctrl(struct file *file, void *fh,
      | ^~~~~~~~~~~~~~~~
v4l2loopback-dc.c:2348:4: error: ‘const struct v4l2_ioctl_ops’ has no member named ‘vidioc_g_ctrl’; did you mean ‘vidioc_g_std’?
 2348 |   .vidioc_g_ctrl            = &vidioc_g_ctrl,
      |    ^~~~~~~~~~~~~
      |    vidioc_g_std
v4l2loopback-dc.c:2348:31: error: initialization of ‘int (*)(struct file *, void *, struct v4l2_dv_timings *)’ from incompatible pointer type ‘int (*)(struct file *, void *, struct v4l2_control *)’ [-Wincompatible-pointer-types]
 2348 |   .vidioc_g_ctrl            = &vidioc_g_ctrl,
      |                               ^
v4l2loopback-dc.c:2348:31: note: (near initialization for ‘v4l2_loopback_ioctl_ops.vidioc_g_dv_timings’)
v4l2loopback-dc.c:1200:1: note: ‘vidioc_g_ctrl’ declared here
 1200 | vidioc_g_ctrl(struct file *file, void *fh,
      | ^~~~~~~~~~~~~
v4l2loopback-dc.c:2349:4: error: ‘const struct v4l2_ioctl_ops’ has no member named ‘vidioc_s_ctrl’; did you mean ‘vidioc_s_std’?
 2349 |   .vidioc_s_ctrl            = &vidioc_s_ctrl,
      |    ^~~~~~~~~~~~~
      |    vidioc_s_std
v4l2loopback-dc.c:2349:31: error: initialization of ‘int (*)(struct file *, void *, struct v4l2_dv_timings *)’ from incompatible pointer type ‘int (*)(struct file *, void *, struct v4l2_control *)’ [-Wincompatible-pointer-types]
 2349 |   .vidioc_s_ctrl            = &vidioc_s_ctrl,
      |                               ^
v4l2loopback-dc.c:2349:31: note: (near initialization for ‘v4l2_loopback_ioctl_ops.vidioc_query_dv_timings’)
v4l2loopback-dc.c:1227:1: note: ‘vidioc_s_ctrl’ declared here
 1227 | vidioc_s_ctrl(struct file *file, void *fh,
      | ^~~~~~~~~~~~~
make[4]: *** [/usr/lib/modules/6.15.2-zen1-1-zen/build/scripts/Makefile.build:203: v4l2loopback-dc.o] Error 1
make[3]: *** [/usr/lib/modules/6.15.2-zen1-1-zen/build/Makefile:2001: .] Error 2
make[2]: *** [/usr/lib/modules/6.15.2-zen1-1-zen/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/v4l2loopback-dc/2.1.3/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.15.2-zen1-1-zen/build'
make: *** [Makefile:8: all] Error 2

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------

```

I hope this error report belongs here? I don't really too much about kernel stuff. Thanks!

**Comment by heftig** [comment]
The external module needs to be updated to support kernel 6.15.
